import { parseFrontmatter, stringifyFrontmatter } from './frontmatter.js';
import { slugify } from './slug.js';
import { stripNoise } from './transcript.js';
import type { MemoryStore } from './store.js';
import { FACT_TYPES, GLOBAL, HearthError, layerId, type Fact, type FactType, type LayerRef } from './types.js';

export function isoDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

export function firstLine(text: string, max = 100): string {
  const line = text.split('\n').map((l) => l.trim()).find((l) => l.length > 0) ?? '';
  return line.length > max ? `${line.slice(0, max - 1).trimEnd()}…` : line;
}

export const DESCRIPTION_MAX = 200;

/**
 * Descriptions become single lines of the index and of the session-start context block, so a
 * stored newline was structural spoofing: `description: "harmless\n- INJECTED"` produced two
 * bullets. Collapse to one line, strip harness tags, and clamp the length (H2).
 */
export function singleLine(text: string, max = DESCRIPTION_MAX): string {
  const one = stripNoise(text).replace(/\s+/g, ' ').trim();
  return one.length > max ? `${one.slice(0, max - 1).trimEnd()}…` : one;
}

function asString(v: unknown): string {
  if (v instanceof Date) return isoDate(v);
  return typeof v === 'string' ? v : '';
}

export function parseFact(name: string, raw: string): Fact {
  const parsed = parseFrontmatter(raw);
  const data = parsed.data;
  const meta = (typeof data.metadata === 'object' && data.metadata ? data.metadata : {}) as Record<string, unknown>;
  const body = parsed.content.trim();
  const type = FACT_TYPES.includes(meta.type as FactType) ? (meta.type as FactType) : 'reference';
  return {
    name: asString(data.name) || name,
    description: asString(data.description) || firstLine(body),
    type,
    created: asString(meta.created),
    device: asString(meta.device),
    pinned: meta.pinned === true,
    body,
  };
}

export function serializeFact(f: Fact): string {
  return stringifyFrontmatter(`${f.body}\n`, {
    name: f.name,
    description: f.description,
    metadata: { type: f.type, created: f.created, device: f.device, pinned: f.pinned },
  });
}

export interface WriteFactInput {
  layer: LayerRef;
  text: string;
  name?: string;
  description?: string;
  type?: FactType;
  pinned?: boolean;
  device: string;
  now?: Date;
}

export async function writeFact(store: MemoryStore, input: WriteFactInput): Promise<Fact> {
  const body = input.text.trim();
  if (!body) throw new HearthError('A fact needs some text.');
  const name = input.name ?? slugify(body.split(/\s+/).slice(0, 6).join(' '));
  if (!name) throw new HearthError('Could not derive a name from that text. Pass --name.');
  const existingRaw = await store.readFact(input.layer, name);
  const prev = existingRaw === null ? null : parseFact(name, existingRaw);
  const fact: Fact = {
    name,
    description: singleLine(input.description ?? firstLine(body)),
    type: input.type ?? prev?.type ?? 'reference',
    created: prev?.created || isoDate(input.now ?? new Date()),
    device: input.device,
    pinned: input.pinned ?? prev?.pinned ?? false,
    body,
  };
  await store.writeFact(input.layer, name, serializeFact(fact));
  await regenerateIndex(store, input.layer);
  return fact;
}

export async function readFact(store: MemoryStore, layer: LayerRef, name: string): Promise<Fact | null> {
  const raw = await store.readFact(layer, name);
  return raw === null ? null : parseFact(name, raw);
}

export async function listFacts(store: MemoryStore, layer: LayerRef): Promise<Fact[]> {
  const out: Fact[] = [];
  for (const name of await store.listFacts(layer)) {
    const f = await readFact(store, layer, name);
    if (f) out.push(f);
  }
  return out;
}

export async function deleteFact(store: MemoryStore, layer: LayerRef, name: string): Promise<boolean> {
  const ok = await store.deleteFact(layer, name);
  if (ok) await regenerateIndex(store, layer);
  return ok;
}

export function indexLine(f: Fact): string {
  const flags = `${f.type}${f.pinned ? ', pinned' : ''}`;
  const conflict = f.name.includes('.conflict-') ? ' (conflict copy)' : '';
  return `- ${f.name}: ${singleLine(f.description)} [${flags}]${conflict}`;
}

export function renderIndex(layer: LayerRef, facts: Fact[]): string {
  const sorted = [...facts].sort((a, b) => a.name.localeCompare(b.name));
  const lines = [`# Memory index: ${layerId(layer)}`, '', '<!-- generated by hearthkit; do not edit by hand -->', ''];
  lines.push(...(sorted.length === 0 ? ['(no facts yet)'] : sorted.map(indexLine)));
  return `${lines.join('\n')}\n`;
}

export async function regenerateIndex(store: MemoryStore, layer: LayerRef): Promise<string> {
  const content = renderIndex(layer, await listFacts(store, layer));
  await store.writeIndex(layer, content);
  return content;
}

export async function promoteFact(store: MemoryStore, name: string, from: LayerRef): Promise<Fact> {
  if (from.kind !== 'project') {
    throw new HearthError('promote moves a fact from a project layer to global. Pass --from project or --from project:<slug>.');
  }
  const fact = await readFact(store, from, name);
  if (!fact) throw new HearthError(`No fact named "${name}" in ${layerId(from)}.`);
  if ((await store.readFact(GLOBAL, name)) !== null) {
    throw new HearthError(`global already has a fact named "${name}". Compare them with: hearth memory show global ${name}`);
  }
  await store.writeFact(GLOBAL, name, serializeFact(fact));
  await store.deleteFact(from, name);
  await regenerateIndex(store, from);
  await regenerateIndex(store, GLOBAL);
  return fact;
}
